/**
 * Service worker registration. Generated by vite-plugin-pwa at build time; in
 * dev there is nothing to register, so this is a no-op.
 */
export function registerSW(): void {
  if (!('serviceWorker' in navigator)) return;
  if (!import.meta.env.PROD) return;
  window.addEventListener('load', () => {
    // Resolved against the deployed base, so it works from a Pages subpath.
    const url = `${import.meta.env.BASE_URL}sw.js`.replace(/\/{2,}/g, '/');
    navigator.serviceWorker.register(url).catch(() => {
      // An unavailable service worker must never break the game.
    });
  });
}
