/**
 * Service worker registration. Generated by vite-plugin-pwa at build time; in
 * dev there is nothing to register, so this is a no-op.
 */
export function registerSW(): void {
  if (!('serviceWorker' in navigator)) return;
  if (!import.meta.env.PROD) return;
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch(() => {
      // An unavailable service worker must never break the game.
    });
  });
}
